[tool.poetry]
name = "llm-eval"
version = "0.1.0"
description = ""
authors = ["Hamza AZIZ"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
inspect-ai = "^0.3.9"
openai = "^1.30.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
